language: c
arch:
  - arm64 
os: linux
dist: focal

compiler:
  - gcc

before_script:
  - sudo apt install build-essential -y
  - cd C-edition
  - mkdir build/
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make
  - sudo make install
