name: Build-arm64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-arm64:
    runs-on: ubuntu-latest
    name: Build-arm64 
    steps:
      - uses: actions/checkout@v2
      - uses: darsvador/run-on-arch-action@v1.0.10
        with:
          architecture: aarch64
          distribution: ubuntu20.04
          run: |
            DEBIAN_FRONTEND=noninteractive apt update
            DEBIAN_FRONTEND=noninteractive apt install build-essential cmake gcc make -y
            cd C-edition/
            mkdir build
            cd build
            cmake ..
            make
            
