name: Build-armv7l

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build-arm64:
    runs-on: ubuntu-latest
    name: Build-armv7l
    steps:
      - uses: actions/checkout@v2
      - uses: darsvador/run-on-arch-action@v1.0.10
        with:
          architecture: armv7
          distribution: ubuntu20.04
          run: |
            DEBIAN_FRONTEND=noninteractive apt update
            DEBIAN_FRONTEND=noninteractive apt install build-essential cmake gcc make -y
            cd C-edition/
            mkdir build
            cd build
            cmake ..
            make -j4
            
      - name: gen-date
        run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV
        
      - name: prepare-upload
        run: |
          cd C-edition/build
          mkdir aptpac-armv7_$DATE/
          mv ./aptpac aptpac-armv7_$DATE/
          cd aptpac-armv7_$DATE/
          echo -e "\n armv7 aptpac daily build for $DATE
          ===================================\n" > README.txt
  
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: aptpac-armv7_${{ env.DATE }}
          path: C-edition/build/aptpac-armv7_${{ env.DATE }}/
