# This is a basic workflow to help you get started with Actions

name: Build-arm64

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64
    - name: Run prebuild outside of QEMU emulator
      run: |
        cd C-edition/
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Releaase ..
    - name: Build for arm64 (aka arm64v8)
      uses: docker://arm64v8/node:14-buster
      with:
        args: bash -c "cd C-edition/build && make"
