name: Build-arm64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-latest
    name: Build arm64
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: prepare
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          githubToken: ${{ github.token }}
          run: |
            sudo apt install build-essential -y
            cd C-edition
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make
            
            
