name: release-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt -y install build-essential tar
      - name: Configure
        run: |
          cd C-edition
          mkdir build
      - name: Build
        run: |
          cd C-edition/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j4
          
      - name: gen-date
        run: echo "DATE=$(date +"%F")" >> $GITHUB_ENV
        
      - name: prepare-upload
        run: |
          cd C-edition/build
          mkdir $DATE/
          mv aptpac $DATE/
          cd $DATE/
          echo -e "\naptpac daily build for $DATE
          =========================================\n" > README.txt
  
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: executable
          path: C-edition/build/aptpac/${{ env.DATE }}/
          
